baseURL = "https://niklas-olsson.github.io/"
languageCode = "en-us"
title = "Random Itch"
theme = "hermit-v2"
publishDir = "docs"

[params]
  [params.author]
  name = "Niklas Olsson"
  description = "A collection of distilled wisdom, conclusions, and reviews."
  footerCopyright = "Â© 2025"
  
  code_copy_button = true
  scrollToTop = true
  readTime = true
  listLayout = ["description", "tags"]
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Insights"
    url = "/insights"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 20
  [[menu.main]]
    name = "Waypoints"
    url = "/waypoints"
    weight = 30

[taxonomies]
  tag = "tags"
